# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
email: me@r14d.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
# twitter_username: jekyllrb
# github_username:  jekyll


# Build settings
markdown: kramdown
highlighter: rouge

# Hyde config

# Permalinks
permalink:        pretty
paginate: 5
# paginate_path: "page:num"

# Setup
title:            r14d
tagline:          'A tagline'
description:      'A description'
url:              http://r14d.com
baseurl:          ""
version: 0.0.1

gems:
  - jekyll-paginate
  - jekyll-gist

repository: r14d/r14d.github.io

github:
  repo: https://github.com/r14d

twitter:
  username: _r14d
