# Site settings
description: > 
  A collection of notes and observations from various coding projects.
baseurl:          ""
twitter_username: _r14d
github_username:  r14d


# Build settings
markdown:         kramdown
highlighter:      rouge

# Hyde config

# Permalinks
permalink:        pretty
paginate:         5

# Setup
title:            r14d
tagline:          Notes from the trenches
url:              http://r14d.com

gems:
  - jekyll-paginate
  - jekyll-gist


